#!/bin/bash
# Verify Migration 022: Check if metadata column exists

echo "================================================================================"
echo "VERIFYING MIGRATION 022: Metadata column in messages table"
echo "================================================================================"
echo ""

# Read the migration SQL
MIGRATION_FILE="migrations/022_add_messages_metadata_column.sql"

if [ ! -f "$MIGRATION_FILE" ]; then
    echo "❌ ERROR: Migration file not found: $MIGRATION_FILE"
    exit 1
fi

echo "✅ Migration file found: $MIGRATION_FILE"
echo ""
echo "================================================================================"
echo "VERIFICATION INSTRUCTIONS"
echo "================================================================================"
echo ""
echo "To verify the migration was applied successfully:"
echo ""
echo "1. Open Supabase SQL Editor:"
echo "   https://supabase.com/dashboard/project/quizuqhnapsemfvjublt/sql"
echo ""
echo "2. Run this verification query:"
echo ""
echo "   SELECT column_name, data_type, is_nullable, column_default"
echo "   FROM information_schema.columns"
echo "   WHERE table_schema = 'public'"
echo "     AND table_name = 'messages'"
echo "     AND column_name = 'metadata';"
echo ""
echo "3. Expected result:"
echo "   - column_name: metadata"
echo "   - data_type: jsonb"
echo "   - is_nullable: YES"
echo "   - column_default: NULL"
echo ""
echo "================================================================================"
echo "NEXT STEPS AFTER VERIFICATION"
echo "================================================================================"
echo ""
echo "If the migration was successful:"
echo ""
echo "1. ✅ The metadata column exists in the messages table"
echo "2. ✅ PostgREST schema cache has been reloaded"
echo "3. 🔄 Restart your backend server (if running locally)"
echo "4. 🧪 Test image generation:"
echo "   - Open Walter in your browser"
echo "   - Ask: 'generate an image of a dog catching a frisbee'"
echo "   - You should see the image appear in the chat"
echo ""
echo "If you see any errors, check:"
echo "- Browser console for frontend errors"
echo "- Backend logs for API errors"
echo "- Supabase logs for database errors"
echo ""
echo "================================================================================"
