-- Migration: 026_compass_status_reports
-- Description: Career status report storage for Compass agent
-- Created: 2026-01-20

-- Career status reports table
CREATE TABLE IF NOT EXISTS compass_status_reports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    client_id UUID NOT NULL REFERENCES clients(id) ON DELETE CASCADE,

    -- Report period
    report_date DATE NOT NULL DEFAULT CURRENT_DATE,
    period_start DATE,
    period_end DATE,

    -- Scores (1-5 scale)
    strategic_impact INTEGER CHECK (strategic_impact >= 1 AND strategic_impact <= 5),
    execution_quality INTEGER CHECK (execution_quality >= 1 AND execution_quality <= 5),
    relationship_building INTEGER CHECK (relationship_building >= 1 AND relationship_building <= 5),
    growth_mindset INTEGER CHECK (growth_mindset >= 1 AND growth_mindset <= 5),
    leadership_presence INTEGER CHECK (leadership_presence >= 1 AND leadership_presence <= 5),
    overall_score DECIMAL(3,2),

    -- AI-generated content
    executive_summary TEXT,
    strategic_impact_justification TEXT,
    execution_quality_justification TEXT,
    relationship_building_justification TEXT,
    growth_mindset_justification TEXT,
    leadership_presence_justification TEXT,

    -- Evidence and recommendations
    wins_referenced JSONB DEFAULT '[]',
    areas_of_strength TEXT[] DEFAULT '{}',
    growth_opportunities TEXT[] DEFAULT '{}',
    recommended_actions TEXT[] DEFAULT '{}',

    -- Metadata
    data_sources JSONB DEFAULT '{}',
    generation_model TEXT DEFAULT 'claude-sonnet-4-20250514',

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_compass_reports_user_date
    ON compass_status_reports(user_id, report_date DESC);

CREATE INDEX IF NOT EXISTS idx_compass_reports_client
    ON compass_status_reports(client_id);

-- Enable RLS
ALTER TABLE compass_status_reports ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view their own reports"
    ON compass_status_reports FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own reports"
    ON compass_status_reports FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own reports"
    ON compass_status_reports FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own reports"
    ON compass_status_reports FOR DELETE
    USING (auth.uid() = user_id);

-- Service role bypass for backend operations
CREATE POLICY "Service role has full access"
    ON compass_status_reports FOR ALL
    USING (auth.role() = 'service_role');

-- Updated at trigger
CREATE OR REPLACE FUNCTION update_compass_reports_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_compass_reports_updated_at
    BEFORE UPDATE ON compass_status_reports
    FOR EACH ROW
    EXECUTE FUNCTION update_compass_reports_updated_at();

-- Comment
COMMENT ON TABLE compass_status_reports IS 'Career status reports generated by Compass agent with 5-dimension rubric scores';
